### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by RastaDollo** [Noname400/Hunt-to-Mnemonic#19]
```
 python3 PulsarMTv4.py -b 44 -db BF/1btc.bf -th 2 -m s -bit 128 -sl 5 -em -bal -dbg 2
Traceback (most recent call last):
  File "PulsarMTv4.py", line 4, in <module>
    from funcP import *
  File "/home/rastadollo/Hunt-to-Mnemonic/funcP.py", line 5, in <module>
    from consts import *
  File "/home/rastadollo/Hunt-to-Mnemonic/consts.py", line 13, in <module>
    import secp256k1_lib
  File "/home/rastadollo/Hunt-to-Mnemonic/secp256k1_lib.py", line 27, in <module>
    ice = ctypes.CDLL(pathdll)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/rastadollo/Hunt-to-Mnemonic/ice_secp256k1.so: wrong ELF class: ELFCLASS64
```
не могу понять чего не хватает
подозреваю что стоит xubuntu 32bit

**Comment by Noname400** [comment]
32 бита нельзя.

**Comment by RastaDollo** [comment]
Установил 64bit, всё заработало.

Единственное помучился с описанием установки mnemonic. В readme написано что можно просто pip install mnemonic сделать, но программа ругается на отсутствие мнемоник, и только mnemonic-for-hunt прокатило.

**Comment by Vladimir855** [comment]
Какие адреса принимает в h160 ? Такие принимает 3cvb  bc5gjyr?

**Comment by Noname400** [comment]
Только 1 и 3

**Comment by Noname400** [comment]
Бип 84 нет
