### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VuzzyM** [Noname400/Hunt-to-Mnemonic#3]
root@Home-PC:/home/ion/Downloads/Hunt-to-Mnemonic-main# python3 mainMT2-hash.py -b 44 -d BF -t 2 -m s -w 12 -c Local_win
------------------------------------------------------------
* Version:  Pulsar v3.6.2 multiT Hash160 
* Total kernel of CPU: 2 
* Used kernel: 2 
* Mode Search: BIP-44 Standart 
* Dir database Bloom Filter: BF 
* Languages at work: ['english'] 
---------------Load BF---------------
Bloom Filter 44.bf Loaded
File address pazzle BTC~30 Loaded.
-------------------------------------
Process CPU/0:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "mainMT2-hash.py", line 1034, in run44
    work44(bf_44,mode,words,debug,list30)
  File "mainMT2-hash.py", line 556, in work44
    bip_obj_acc = bip_obj_mst.Purpose().Coin().Account(0)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip44.py", line 135, in Purpose
    return self._PurposeGeneric(self)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip44_base.py", line 364, in _PurposeGeneric
    return cls(bip_obj.m_bip32.ChildKey(cls._GetPurpose()), bip_obj.m_coin_type)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip32.py", line 236, in ChildKey
    return self.__CkdPriv(index) if not self.m_is_public else self.__CkdPub(index)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip32.py", line 421, in __CkdPriv
    secret = ConvUtils.IntegerToBytes(new_key_int)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/utils/conversion.py", line 57, in IntegerToBytes
    return data_int.to_bytes((data_int.bit_length() + 7) // 8, endianness)
AttributeError: 'mpz' object has no attribute 'to_bytes'
Process CPU/1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "mainMT2-hash.py", line 1034, in run44
    work44(bf_44,mode,words,debug,list30)
  File "mainMT2-hash.py", line 556, in work44
    bip_obj_acc = bip_obj_mst.Purpose().Coin().Account(0)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip44.py", line 135, in Purpose
    return self._PurposeGeneric(self)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip44_base.py", line 364, in _PurposeGeneric
    return cls(bip_obj.m_bip32.ChildKey(cls._GetPurpose()), bip_obj.m_coin_type)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip32.py", line 236, in ChildKey
    return self.__CkdPriv(index) if not self.m_is_public else self.__CkdPub(index)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/bip/bip32.py", line 421, in __CkdPriv
    secret = ConvUtils.IntegerToBytes(new_key_int)
  File "/usr/local/lib/python3.8/dist-packages/bip_utils/utils/conversion.py", line 57, in IntegerToBytes
    return data_int.to_bytes((data_int.bit_length() + 7) // 8, endianness)
AttributeError: 'mpz' object has no attribute 'to_bytes'
root@Home-PC:/home/ion/Downloads/Hunt-to-Mnemonic-main# 

Все пакеты установлены , я использую linux mint

**Comment by Noname400** [comment]
покажите ваши пэкаджи 
pip list

**Comment by Noname400** [comment]
версия bip_utils == 1.11.1
если есть gmpy или gmpy2 их надо удалить

**Comment by Noname400** [comment]
pip3 uninstall gmpy
pip3 uninstall gmpy2

**Comment by VuzzyM** [comment]
> pip3 uninstall gmpy
> pip3 uninstall gmpy2

Теперь работает, спасибо
