### ISSUE TITLE
Проблема с запуском.

### ISSUE THREAD

**Issue by Delti42** [Noname400/Hunt-to-Mnemonic#43]
DEPENDENCY TESTING:
Traceback (most recent call last):
  File "PulsarMTv5.py", line 138, in <module>
    if test():
  File "/home/dregan/Utils/Hunt-to-Mnemonic-main/funcP.py", line 672, in test
    pvk = bip32.get_privkey_from_path(patchs)
  File "/home/dregan/.local/lib/python3.8/site-packages/bip32/bip32.py", line 73, in get_privkey_from_path
    return self.get_extended_privkey_from_path(path)[1]
  File "/home/dregan/.local/lib/python3.8/site-packages/bip32/bip32.py", line 58, in get_extended_privkey_from_path
    if index & HARDENED_INDEX:
TypeError: unsupported operand type(s) for &: 'str' and 'int'
 

Что можно с этим сделать?

**Comment by Delti42** [comment]
Проблема решена. Нужно обновить bip32

**Comment by Gr77veDealer** [comment]
в чем была причина бро?Такая же шняга,понять не могу
