### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dizelekss** [Noname400/Hunt-to-Mnemonic#53]
Traceback (most recent call last):
  File "PulsarMTv5.py", line 8, in <module>
    from funcP import *
  File "C:\Users\User\Desktop\Hunt-to-Mnemonic-main\funcP.py", line 7, in <module>
    from consts import *
  File "C:\Users\User\Desktop\Hunt-to-Mnemonic-main\consts.py", line 26, in <module>
    import cryptos
ModuleNotFoundError: No module named 'cryptos'

**Comment by dizelekss** [comment]
отбой

**Comment by Gr77veDealer** [comment]
в чем была причина бро?у меня такая же шняга,не могу понять

**Comment by dizelekss** [comment]
pip install cryptos

**Comment by Gr77veDealer** [comment]
фенкью
