### ISSUE TITLE
Ошибка при установки пакета  bitcoinlib python 3.10

### ISSUE THREAD

**Issue by Arsiprog** [Noname400/Hunt-to-Mnemonic#57]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

**Comment by Arsiprog** [comment]
![image](https://user-images.githubusercontent.com/45854657/160258466-2a5653f2-ee9e-4500-8d70-7c23e669c035.png)

**Comment by Arsiprog** [comment]
\btc_pulsar>python3 -B PulsarMTv5.py -b BTC -dbbtc BF\btc.bf -th 3 -des Noname -m e -sl 7 -elec
Traceback (most recent call last):
  File "C:\btc_pulsar\PulsarMTv5.py", line 8, in <module>
    from funcP import *
  File "C:\btc_pulsar\funcP.py", line 7, in <module>
    from consts import *
  File "C:\btc_pulsar\consts.py", line 20, in <module>
    import smtplib, socket, string, sys, ecdsa, hashlib, pbkdf2
ModuleNotFoundError: No module named 'ecdsa'

C:\btc_pulsar>pause
Для продолжения нажмите любую клавишу . . .

**Comment by Noname400** [comment]
в описании указано установка MSBUILD

**Comment by LamerStore** [comment]
@Noname400 У меня такая же проблема, на Windows Server 2019. MSBUILD установлен

**Comment by Noname400** [comment]
решили проблему ?
