### ISSUE TITLE
Не получается запустить на Ubuntu

### ISSUE THREAD

**Issue by LamerStore** [Noname400/Hunt-to-Mnemonic#58]
Не получается запустить на Ubuntu, на Windows Server работает. 

![image](https://user-images.githubusercontent.com/83141598/161376547-4ba438e3-041f-45f0-8030-425f31290b06.png)

ubuntu@instance-20220320-2051:~/Hunt$ python3 -B PulsarMTv5.py -b combo -dbbtc BF\btc.bf -dbeth BF\eth.bf -th 4 -des source -m e -bit 128 -sl 5 -bal -rnd -elec -brain -telegram
Traceback (most recent call last):
  File "PulsarMTv5.py", line 8, in <module>
    from funcP import *
  File "/home/ubuntu/Hunt/funcP.py", line 7, in <module>
    from consts import *
  File "/home/ubuntu/Hunt/consts.py", line 25, in <module>
    import secp256k1_lib
  File "/home/ubuntu/Hunt/secp256k1_lib.py", line 29, in <module>
    ice = ctypes.CDLL(pathdll)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/Hunt/ice_secp256k1.so: cannot open shared object file: No such file or directory
ubuntu@instance-20220320-2051:~/Hunt$

**Comment by Noname400** [comment]
версия ubuntu
сделайте sudo apt update

**Comment by LamerStore** [comment]
Порпобовал снесни убунту и поставить заного, не помогло.

Версия Ubuntu 20.04.4 

Можешь оставить телеграм свой может? В профиле видимо старый.

**Comment by Noname400** [comment]
@NonameHunt
